apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres
spec:
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.existingSecret | default "postgres-secret" }}
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.existingSecret | default "postgres-secret" }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.existingSecret | default "postgres-secret" }}
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U kubestack -d kubestack
            initialDelaySeconds: {{ .Values.postgres.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.postgres.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.postgres.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.postgres.probes.readiness.failureThreshold }}
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U kubestack -d kubestack
            initialDelaySeconds: {{ .Values.postgres.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.postgres.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.postgres.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.postgres.probes.liveness.failureThreshold }}
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
