namespace: kubestack

backend:
  replicaCount: 1
  image:
    repository: kubestack-backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000
  databaseUrl: postgresql+psycopg2://kubestack:kubestack_dev_password@postgres:5432/kubestack
  existingSecret: ""
  probes:
    readiness:
      initialDelaySeconds: 15
      periodSeconds: 5
      timeoutSeconds: 5
      failureThreshold: 3
    liveness:
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3

frontend:
  replicaCount: 1
  image:
    repository: kubestack-frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 80
    targetPort: 80
  probes:
    readiness:
      initialDelaySeconds: 5
      periodSeconds: 5
    liveness:
      initialDelaySeconds: 15
      periodSeconds: 10

postgres:
  replicaCount: 1
  image:
    repository: postgres
    tag: "16"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5432
    targetPort: 5432
  database: kubestack
  username: kubestack
  password: kubestack_dev_password
  existingSecret: ""
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
  probes:
    readiness:
      initialDelaySeconds: 20
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
    liveness:
      initialDelaySeconds: 60
      periodSeconds: 15
      timeoutSeconds: 5
      failureThreshold: 6
