name: KubeStack CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  ECR_REGISTRY: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com

jobs:
  build-and-push:
    name: Build and Push Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/kubestack-github-actions-role
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tag
        id: image
        run: echo "tag=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Build backend image
        run: |
          docker build \
            -t $ECR_REGISTRY/kubestack-backend:${{ steps.image.outputs.tag }} \
            ./backend

      - name: Build frontend image
        run: |
          docker build \
            -t $ECR_REGISTRY/kubestack-frontend:${{ steps.image.outputs.tag }} \
            ./frontend

      - name: Push backend image
        run: |
          docker push \
            $ECR_REGISTRY/kubestack-backend:${{ steps.image.outputs.tag }}

      - name: Push frontend image
        run: |
          docker push \
            $ECR_REGISTRY/kubestack-frontend:${{ steps.image.outputs.tag }}